import { ComponentDefinition } from "@/lib/types";

export const awsComponents: ComponentDefinition[] = [
  // ====================== COMPUTE ======================
  {
    id: "aws-ec2",
    name: "EC2 Instance",
    description: "Amazon Elastic Compute Cloud virtual server",
    category: "compute",
    provider: "aws",
    icon: "Server",
    color: "orange",
    ports: [
      { id: "ec2-in", type: "input", label: "Inbound", allowedTypes: ["aws-vpc", "aws-sg", "aws-elb", "aws-nat-gw"], position: "top" },
      { id: "ec2-out", type: "output", label: "Outbound", allowedTypes: ["aws-ebs", "aws-s3", "aws-rds", "aws-dynamodb"], position: "bottom" },
    ],
    configFields: [
      { key: "instance_type", label: "Instance Type", type: "select", required: true, defaultValue: "t3.micro", options: [
        { label: "t3.micro", value: "t3.micro" }, { label: "t3.small", value: "t3.small" },
        { label: "t3.medium", value: "t3.medium" }, { label: "t3.large", value: "t3.large" },
        { label: "m5.large", value: "m5.large" }, { label: "m5.xlarge", value: "m5.xlarge" },
        { label: "c5.large", value: "c5.large" }, { label: "r5.large", value: "r5.large" },
      ]},
      { key: "ami", label: "AMI ID", type: "text", placeholder: "ami-0abcdef1234567890", description: "Amazon Machine Image ID" },
      { key: "key_name", label: "Key Pair Name", type: "text", placeholder: "my-key-pair" },
      { key: "associate_public_ip", label: "Public IP", type: "boolean", defaultValue: false, description: "Associate a public IP address" },
      { key: "root_volume_size", label: "Root Volume Size (GB)", type: "number", defaultValue: 20, validation: { min: 8, max: 16384 } },
      { key: "tags_name", label: "Name Tag", type: "text", placeholder: "my-instance" },
    ],
    terraformMapping: {
      resourceType: "aws_instance",
      module: "terraform-aws-modules/ec2-instance/aws",
      moduleVersion: "~> 5.0",
      configMapping: {
        instance_type: "instance_type",
        ami: "ami",
        key_name: "key_name",
        associate_public_ip: "associate_public_ip_address",
        root_volume_size: "root_block_device.volume_size",
        tags_name: "tags.Name",
      },
      outputs: { instance_id: "id", public_ip: "public_ip", private_ip: "private_ip" },
    },
    defaultConfig: { instance_type: "t3.micro", associate_public_ip: false, root_volume_size: 20 },
  },
  {
    id: "aws-lambda",
    name: "Lambda Function",
    description: "AWS serverless compute function",
    category: "compute",
    provider: "aws",
    icon: "Zap",
    color: "orange",
    ports: [
      { id: "lambda-in", type: "input", label: "Trigger", allowedTypes: ["aws-api-gw", "aws-s3", "aws-dynamodb", "aws-elb"], position: "top" },
      { id: "lambda-out", type: "output", label: "Access", allowedTypes: ["aws-s3", "aws-dynamodb", "aws-rds", "aws-iam"], position: "bottom" },
    ],
    configFields: [
      { key: "function_name", label: "Function Name", type: "text", required: true, placeholder: "my-function" },
      { key: "runtime", label: "Runtime", type: "select", required: true, defaultValue: "nodejs20.x", options: [
        { label: "Node.js 20.x", value: "nodejs20.x" }, { label: "Python 3.12", value: "python3.12" },
        { label: "Java 21", value: "java21" }, { label: "Go 1.x", value: "go1.x" },
        { label: ".NET 8", value: "dotnet8" },
      ]},
      { key: "memory_size", label: "Memory (MB)", type: "number", defaultValue: 128, validation: { min: 128, max: 10240 } },
      { key: "timeout", label: "Timeout (seconds)", type: "number", defaultValue: 3, validation: { min: 1, max: 900 } },
      { key: "handler", label: "Handler", type: "text", defaultValue: "index.handler" },
    ],
    terraformMapping: {
      resourceType: "aws_lambda_function",
      configMapping: {
        function_name: "function_name",
        runtime: "runtime",
        memory_size: "memory_size",
        timeout: "timeout",
        handler: "handler",
      },
      outputs: { function_arn: "arn", function_name: "function_name" },
    },
    defaultConfig: { runtime: "nodejs20.x", memory_size: 128, timeout: 3, handler: "index.handler" },
  },
  // ====================== STORAGE ======================
  {
    id: "aws-s3",
    name: "S3 Bucket",
    description: "Amazon Simple Storage Service bucket",
    category: "storage",
    provider: "aws",
    icon: "Database",
    color: "green",
    ports: [
      { id: "s3-in", type: "input", label: "Access", allowedTypes: ["aws-ec2", "aws-lambda", "aws-iam"], position: "top" },
      { id: "s3-out", type: "output", label: "Events", allowedTypes: ["aws-lambda", "aws-cdn"], position: "bottom" },
    ],
    configFields: [
      { key: "bucket_name", label: "Bucket Name", type: "text", required: true, placeholder: "my-bucket", validation: { pattern: "^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$", message: "Must be a valid S3 bucket name" } },
      { key: "versioning", label: "Versioning", type: "boolean", defaultValue: true },
      { key: "encryption", label: "Server-Side Encryption", type: "select", defaultValue: "AES256", options: [
        { label: "AES-256", value: "AES256" }, { label: "AWS KMS", value: "aws:kms" },
      ]},
      { key: "public_access_block", label: "Block Public Access", type: "boolean", defaultValue: true },
    ],
    terraformMapping: {
      resourceType: "aws_s3_bucket",
      module: "terraform-aws-modules/s3-bucket/aws",
      moduleVersion: "~> 4.0",
      configMapping: {
        bucket_name: "bucket",
        versioning: "versioning.enabled",
        encryption: "server_side_encryption_configuration.rule.apply_server_side_encryption_by_default.sse_algorithm",
      },
      outputs: { bucket_arn: "arn", bucket_id: "id", bucket_domain: "bucket_domain_name" },
    },
    defaultConfig: { versioning: true, encryption: "AES256", public_access_block: true },
  },
  {
    id: "aws-ebs",
    name: "EBS Volume",
    description: "Amazon Elastic Block Store volume",
    category: "storage",
    provider: "aws",
    icon: "HardDrive",
    color: "green",
    ports: [
      { id: "ebs-in", type: "input", label: "Attach", allowedTypes: ["aws-ec2"], position: "top" },
    ],
    configFields: [
      { key: "volume_type", label: "Volume Type", type: "select", defaultValue: "gp3", options: [
        { label: "GP3 (General Purpose SSD)", value: "gp3" }, { label: "GP2", value: "gp2" },
        { label: "IO1 (Provisioned IOPS)", value: "io1" }, { label: "ST1 (Throughput Optimized)", value: "st1" },
      ]},
      { key: "size", label: "Size (GB)", type: "number", required: true, defaultValue: 100, validation: { min: 1, max: 16384 } },
      { key: "encrypted", label: "Encrypted", type: "boolean", defaultValue: true },
    ],
    terraformMapping: {
      resourceType: "aws_ebs_volume",
      configMapping: { volume_type: "type", size: "size", encrypted: "encrypted" },
      outputs: { volume_id: "id" },
    },
    defaultConfig: { volume_type: "gp3", size: 100, encrypted: true },
  },
  // ====================== DATABASE ======================
  {
    id: "aws-rds",
    name: "RDS Database",
    description: "Amazon Relational Database Service",
    category: "database",
    provider: "aws",
    icon: "Database",
    color: "blue",
    ports: [
      { id: "rds-in", type: "input", label: "Connect", allowedTypes: ["aws-ec2", "aws-lambda", "aws-sg", "aws-vpc"], position: "top" },
    ],
    configFields: [
      { key: "engine", label: "Engine", type: "select", required: true, defaultValue: "postgres", options: [
        { label: "PostgreSQL", value: "postgres" }, { label: "MySQL", value: "mysql" },
        { label: "Aurora PostgreSQL", value: "aurora-postgresql" }, { label: "Aurora MySQL", value: "aurora-mysql" },
        { label: "SQL Server", value: "sqlserver-ee" },
      ]},
      { key: "engine_version", label: "Engine Version", type: "text", defaultValue: "16.3" },
      { key: "instance_class", label: "Instance Class", type: "select", defaultValue: "db.t3.micro", options: [
        { label: "db.t3.micro", value: "db.t3.micro" }, { label: "db.t3.small", value: "db.t3.small" },
        { label: "db.t3.medium", value: "db.t3.medium" }, { label: "db.r5.large", value: "db.r5.large" },
        { label: "db.r5.xlarge", value: "db.r5.xlarge" },
      ]},
      { key: "allocated_storage", label: "Storage (GB)", type: "number", defaultValue: 20, validation: { min: 20, max: 65536 } },
      { key: "db_name", label: "Database Name", type: "text", placeholder: "mydb" },
      { key: "multi_az", label: "Multi-AZ Deployment", type: "boolean", defaultValue: false },
      { key: "backup_retention", label: "Backup Retention (days)", type: "number", defaultValue: 7, validation: { min: 0, max: 35 } },
    ],
    terraformMapping: {
      resourceType: "aws_db_instance",
      module: "terraform-aws-modules/rds/aws",
      moduleVersion: "~> 6.0",
      configMapping: {
        engine: "engine", engine_version: "engine_version", instance_class: "instance_class",
        allocated_storage: "allocated_storage", db_name: "db_name", multi_az: "multi_az",
        backup_retention: "backup_retention_period",
      },
      outputs: { endpoint: "endpoint", arn: "arn", address: "address" },
      dependencies: ["aws_vpc", "aws_security_group"],
    },
    defaultConfig: { engine: "postgres", engine_version: "16.3", instance_class: "db.t3.micro", allocated_storage: 20, multi_az: false, backup_retention: 7 },
  },
  {
    id: "aws-dynamodb",
    name: "DynamoDB Table",
    description: "Amazon DynamoDB NoSQL database",
    category: "database",
    provider: "aws",
    icon: "Table",
    color: "blue",
    ports: [
      { id: "dynamo-in", type: "input", label: "Access", allowedTypes: ["aws-ec2", "aws-lambda", "aws-iam"], position: "top" },
      { id: "dynamo-out", type: "output", label: "Stream", allowedTypes: ["aws-lambda"], position: "bottom" },
    ],
    configFields: [
      { key: "table_name", label: "Table Name", type: "text", required: true, placeholder: "my-table" },
      { key: "billing_mode", label: "Billing Mode", type: "select", defaultValue: "PAY_PER_REQUEST", options: [
        { label: "On-Demand", value: "PAY_PER_REQUEST" }, { label: "Provisioned", value: "PROVISIONED" },
      ]},
      { key: "hash_key", label: "Partition Key", type: "text", required: true, placeholder: "id" },
      { key: "range_key", label: "Sort Key", type: "text", placeholder: "timestamp" },
      { key: "stream_enabled", label: "Enable Streams", type: "boolean", defaultValue: false },
    ],
    terraformMapping: {
      resourceType: "aws_dynamodb_table",
      configMapping: {
        table_name: "name", billing_mode: "billing_mode",
        hash_key: "hash_key", range_key: "range_key",
        stream_enabled: "stream_enabled",
      },
      outputs: { table_arn: "arn", table_id: "id" },
    },
    defaultConfig: { billing_mode: "PAY_PER_REQUEST", stream_enabled: false },
  },
  // ====================== NETWORKING ======================
  {
    id: "aws-vpc",
    name: "VPC",
    description: "Amazon Virtual Private Cloud",
    category: "networking",
    provider: "aws",
    icon: "Network",
    color: "purple",
    ports: [
      { id: "vpc-out", type: "output", label: "Contains", allowedTypes: ["aws-ec2", "aws-rds", "aws-elb", "aws-nat-gw", "aws-sg"], position: "bottom" },
    ],
    configFields: [
      { key: "cidr_block", label: "CIDR Block", type: "text", required: true, defaultValue: "10.0.0.0/16", validation: { pattern: "^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}/\\d{1,2}$", message: "Must be valid CIDR" } },
      { key: "name", label: "VPC Name", type: "text", required: true, placeholder: "my-vpc" },
      { key: "enable_dns_hostnames", label: "DNS Hostnames", type: "boolean", defaultValue: true },
      { key: "enable_dns_support", label: "DNS Support", type: "boolean", defaultValue: true },
      { key: "public_subnets", label: "Public Subnets", type: "text", defaultValue: "10.0.1.0/24,10.0.2.0/24", description: "Comma-separated CIDR blocks" },
      { key: "private_subnets", label: "Private Subnets", type: "text", defaultValue: "10.0.10.0/24,10.0.20.0/24", description: "Comma-separated CIDR blocks" },
    ],
    terraformMapping: {
      resourceType: "aws_vpc",
      module: "terraform-aws-modules/vpc/aws",
      moduleVersion: "~> 5.0",
      configMapping: {
        cidr_block: "cidr", name: "name",
        enable_dns_hostnames: "enable_dns_hostnames", enable_dns_support: "enable_dns_support",
        public_subnets: "public_subnets", private_subnets: "private_subnets",
      },
      outputs: { vpc_id: "vpc_id", public_subnet_ids: "public_subnets", private_subnet_ids: "private_subnets" },
    },
    defaultConfig: { cidr_block: "10.0.0.0/16", enable_dns_hostnames: true, enable_dns_support: true, public_subnets: "10.0.1.0/24,10.0.2.0/24", private_subnets: "10.0.10.0/24,10.0.20.0/24" },
  },
  {
    id: "aws-elb",
    name: "Load Balancer",
    description: "Application Load Balancer",
    category: "networking",
    provider: "aws",
    icon: "GitBranch",
    color: "purple",
    ports: [
      { id: "elb-in", type: "input", label: "Traffic", allowedTypes: ["aws-vpc", "aws-api-gw", "aws-cdn"], position: "top" },
      { id: "elb-out", type: "output", label: "Forward", allowedTypes: ["aws-ec2", "aws-lambda"], position: "bottom" },
    ],
    configFields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "my-alb" },
      { key: "lb_type", label: "Type", type: "select", defaultValue: "application", options: [
        { label: "Application", value: "application" }, { label: "Network", value: "network" },
      ]},
      { key: "internal", label: "Internal", type: "boolean", defaultValue: false },
    ],
    terraformMapping: {
      resourceType: "aws_lb",
      module: "terraform-aws-modules/alb/aws",
      moduleVersion: "~> 9.0",
      configMapping: { name: "name", lb_type: "load_balancer_type", internal: "internal" },
      outputs: { alb_arn: "arn", dns_name: "dns_name" },
      dependencies: ["aws_vpc", "aws_security_group"],
    },
    defaultConfig: { lb_type: "application", internal: false },
  },
  {
    id: "aws-api-gw",
    name: "API Gateway",
    description: "Amazon API Gateway (REST/HTTP)",
    category: "networking",
    provider: "aws",
    icon: "Globe",
    color: "purple",
    ports: [
      { id: "apigw-out", type: "output", label: "Routes", allowedTypes: ["aws-lambda", "aws-elb", "aws-ec2"], position: "bottom" },
    ],
    configFields: [
      { key: "name", label: "API Name", type: "text", required: true, placeholder: "my-api" },
      { key: "protocol_type", label: "Protocol", type: "select", defaultValue: "HTTP", options: [
        { label: "HTTP", value: "HTTP" }, { label: "REST", value: "REST" }, { label: "WebSocket", value: "WEBSOCKET" },
      ]},
      { key: "stage_name", label: "Stage Name", type: "text", defaultValue: "prod" },
    ],
    terraformMapping: {
      resourceType: "aws_apigatewayv2_api",
      configMapping: { name: "name", protocol_type: "protocol_type" },
      outputs: { api_id: "id", api_endpoint: "api_endpoint" },
    },
    defaultConfig: { protocol_type: "HTTP", stage_name: "prod" },
  },
  {
    id: "aws-nat-gw",
    name: "NAT Gateway",
    description: "Network Address Translation Gateway",
    category: "networking",
    provider: "aws",
    icon: "ArrowRightLeft",
    color: "purple",
    ports: [
      { id: "nat-in", type: "input", label: "From VPC", allowedTypes: ["aws-vpc"], position: "top" },
      { id: "nat-out", type: "output", label: "Internet", allowedTypes: [], position: "bottom" },
    ],
    configFields: [
      { key: "connectivity_type", label: "Connectivity Type", type: "select", defaultValue: "public", options: [
        { label: "Public", value: "public" }, { label: "Private", value: "private" },
      ]},
    ],
    terraformMapping: {
      resourceType: "aws_nat_gateway",
      configMapping: { connectivity_type: "connectivity_type" },
      outputs: { nat_gw_id: "id" },
      dependencies: ["aws_vpc"],
    },
    defaultConfig: { connectivity_type: "public" },
  },
  {
    id: "aws-cdn",
    name: "CloudFront CDN",
    description: "Amazon CloudFront Content Delivery Network",
    category: "networking",
    provider: "aws",
    icon: "Globe",
    color: "purple",
    ports: [
      { id: "cdn-out", type: "output", label: "Origin", allowedTypes: ["aws-s3", "aws-elb", "aws-ec2"], position: "bottom" },
    ],
    configFields: [
      { key: "price_class", label: "Price Class", type: "select", defaultValue: "PriceClass_100", options: [
        { label: "US, Canada, Europe", value: "PriceClass_100" },
        { label: "US, Canada, Europe, Asia", value: "PriceClass_200" },
        { label: "All Edge Locations", value: "PriceClass_All" },
      ]},
      { key: "default_ttl", label: "Default TTL (seconds)", type: "number", defaultValue: 86400 },
    ],
    terraformMapping: {
      resourceType: "aws_cloudfront_distribution",
      configMapping: { price_class: "price_class", default_ttl: "default_cache_behavior.default_ttl" },
      outputs: { distribution_id: "id", domain_name: "domain_name" },
    },
    defaultConfig: { price_class: "PriceClass_100", default_ttl: 86400 },
  },
  // ====================== SECURITY ======================
  {
    id: "aws-iam",
    name: "IAM Role",
    description: "AWS Identity and Access Management Role",
    category: "security",
    provider: "aws",
    icon: "Shield",
    color: "red",
    ports: [
      { id: "iam-out", type: "output", label: "Assume", allowedTypes: ["aws-ec2", "aws-lambda", "aws-s3", "aws-rds", "aws-dynamodb"], position: "bottom" },
    ],
    configFields: [
      { key: "role_name", label: "Role Name", type: "text", required: true, placeholder: "my-role" },
      { key: "assume_role_policy", label: "Trusted Service", type: "select", defaultValue: "ec2.amazonaws.com", options: [
        { label: "EC2", value: "ec2.amazonaws.com" }, { label: "Lambda", value: "lambda.amazonaws.com" },
        { label: "ECS", value: "ecs-tasks.amazonaws.com" },
      ]},
      { key: "managed_policies", label: "Managed Policies", type: "tags", description: "ARNs of managed policies" },
    ],
    terraformMapping: {
      resourceType: "aws_iam_role",
      configMapping: { role_name: "name", assume_role_policy: "assume_role_policy" },
      outputs: { role_arn: "arn", role_name: "name" },
    },
    defaultConfig: { assume_role_policy: "ec2.amazonaws.com" },
  },
  {
    id: "aws-sg",
    name: "Security Group",
    description: "VPC Security Group for network access control",
    category: "security",
    provider: "aws",
    icon: "Lock",
    color: "red",
    ports: [
      { id: "sg-in", type: "input", label: "VPC", allowedTypes: ["aws-vpc"], position: "top" },
      { id: "sg-out", type: "output", label: "Protect", allowedTypes: ["aws-ec2", "aws-rds", "aws-elb"], position: "bottom" },
    ],
    configFields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "my-sg" },
      { key: "description", label: "Description", type: "text", placeholder: "Security group for..." },
      { key: "ingress_ports", label: "Ingress Ports", type: "text", defaultValue: "80,443", description: "Comma-separated ports" },
      { key: "ingress_cidr", label: "Ingress CIDR", type: "text", defaultValue: "0.0.0.0/0" },
    ],
    terraformMapping: {
      resourceType: "aws_security_group",
      configMapping: { name: "name", description: "description" },
      outputs: { sg_id: "id" },
      dependencies: ["aws_vpc"],
    },
    defaultConfig: { ingress_ports: "80,443", ingress_cidr: "0.0.0.0/0" },
  },
  {
    id: "aws-kms",
    name: "KMS Key",
    description: "AWS Key Management Service encryption key",
    category: "security",
    provider: "aws",
    icon: "Key",
    color: "red",
    ports: [
      { id: "kms-out", type: "output", label: "Encrypt", allowedTypes: ["aws-s3", "aws-ebs", "aws-rds", "aws-dynamodb"], position: "bottom" },
    ],
    configFields: [
      { key: "description", label: "Description", type: "text", placeholder: "Encryption key for..." },
      { key: "key_usage", label: "Key Usage", type: "select", defaultValue: "ENCRYPT_DECRYPT", options: [
        { label: "Encrypt/Decrypt", value: "ENCRYPT_DECRYPT" }, { label: "Sign/Verify", value: "SIGN_VERIFY" },
      ]},
      { key: "enable_rotation", label: "Enable Key Rotation", type: "boolean", defaultValue: true },
    ],
    terraformMapping: {
      resourceType: "aws_kms_key",
      configMapping: { description: "description", key_usage: "key_usage", enable_rotation: "enable_key_rotation" },
      outputs: { key_id: "key_id", key_arn: "arn" },
    },
    defaultConfig: { key_usage: "ENCRYPT_DECRYPT", enable_rotation: true },
  },
];
